### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Christoph999** [paleo13/rgurobi#1]
Hi Jeff, I tried to install the package, but the following error occured:

[Seems to me as if it went fine...]
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o rgurobi.dll tmp.def RcppExports.o solve_gurobi.o -LC:\gurobi752\win64/lib -lgurobi_c++ -lgurobi70 -LC:/R/R-34~1.4/bin/x64 -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgurobi_c++
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgurobi70
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'rgurobi'
* removing 'C:/R/R-3.4.4/library/rgurobi'
In R CMD INSTALL
Installation failed: Command failed (1)

Do you have an idea what went wrong? I am using RStudio and 
find_rtools() gives [1] TRUE

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for getting in touch. 

Yeah the package was assuming that you have Gurobi version 7.0.X installed. Since the latest version of Gurobi is 7.5.2, I've updated the package to assume that version 7.5.X is installed. 

Unfortunately, I don't know how to systematically determine which version of Gurobi is installed on a given system, so the best I can do is just update this package along with the latest version of Gurobi. 

If you need this package to work with an older version of Gurobi, then you just need to update the text `-lgurobi75` in the file src/Makevars to correspond with the desired version of Gurobi (e.g. `-lgurobi70` for version 7.0.X).

Could you try installing the package again, and let me know if that fixes it?

**Comment by Christoph999** [comment]
Thanks for your reply :-) Unfortunatelly, there is still an error. After pulling - now the full output:

> devtools:::install_github('paleo13/rgurobi')

```
Downloading GitHub repo paleo13/rgurobi@master
from URL https://api.github.com/repos/paleo13/rgurobi/zipball/master
Installing rgurobi
"C:/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/sqc/AppData/Local/Temp/RtmpEdaFqY/devtools23e03dcb4529/jeffreyhanson-rgurobi-ce6d776" --library="C:/R/R-3.4.4/library" --install-tests 

* installing *source* package 'rgurobi' ...
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-34~1.4/include" -DNDEBUG -I"C:\gurobi752\win64/include" -lm  -I"C:/R/R-3.4.4/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-34~1.4/include" -DNDEBUG -I"C:\gurobi752\win64/include" -lm  -I"C:/R/R-3.4.4/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c solve_gurobi.cpp -o solve_gurobi.o
solve_gurobi.cpp: In function 'Rcpp::List solve_gurobi(Rcpp::List, std::vector<std::basic_string<char> >, std::vector<std::basic_string<char> >, std::size_t, bool)':
solve_gurobi.cpp:42:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (std::size_t i=0; i<ncol; ++i) vtype_char[i]=vtype[i][0];
                         ^
solve_gurobi.cpp:44:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (std::size_t i=0; i<nrow; ++i) sense_char[i]=sense[i][0];
                         ^
solve_gurobi.cpp:46:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (std::size_t i=0; i<nrow; ++i) names[i]="C"+std::to_string(i);
                         ^
solve_gurobi.cpp:63:15: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  if (lb.size()>0 & ub.size()>0) {
               ^
solve_gurobi.cpp:65:22: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  } else if (lb.size()>0 & ub.size()==0) {
                      ^
solve_gurobi.cpp:67:22: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  } else if (lb.size()==0 & ub.size()>0) {
                      ^
solve_gurobi.cpp:69:22: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  } else if (lb.size()==0 & ub.size()==0) {
                      ^
solve_gurobi.cpp:86:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (std::size_t i=0; i<nrow; ++i)
                         ^
solve_gurobi.cpp:123:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (std::size_t j=0; j<ncol; ++j) {
                          ^
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o rgurobi.dll tmp.def RcppExports.o solve_gurobi.o -LC:\gurobi752\win64/lib -lgurobi_c++ -lgurobi75 -LC:/R/R-34~1.4/bin/x64 -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgurobi_c++
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'rgurobi'
* removing 'C:/R/R-3.4.4/library/rgurobi'
In R CMD INSTALL
Installation failed: Command failed (1)
```

**Comment by jeffreyhanson** [comment]
Hmm, I haven't seen that error before. Maybe one of the environmental variables is missing? Did you set up the environmental variables for Gurobi (i.e. `GUROBI_HOME` and `LD_LIBRARY_PATH`, and add `GUROBI_HOME/bin` to `PATH`)? Also, were you able to install the gurobi R package distributed with Gurobi?

**Comment by Christoph999** [comment]
I installed Gurobi and it is working fine: I can even call it from R, e.g. gurobi::gurobi(...).

**Comment by jeffreyhanson** [comment]
It turns out that Gurobi cannot be compiled using the GCC toolchain on Windows (http://www.gurobi.com/products/supported-platforms), so I guess this means that this package can't be compiled using rtools. 

So, it looks like this package never worked on Windows and I either just never got around to testing this, or I simply forgot this because it's been so long since I've looked at this repo.

I'm sorry I don't have a more helpful solution.

**Comment by Christoph999** [comment]
No problem, but thank's for clarification!

**Comment by Christoph999** [comment]
Hi Jeff, as you know, I started to work with Gurobi and it seems you know quite a lot ;-) It would be great if you can have a look at that question on [SO](https://stackoverflow.com/q/49813500/5784831). Maybe the answer is really simple, but I could not find out...

**Comment by jeffreyhanson** [comment]
I've just posted a reply on SO, hopefully that helps.

**Comment by Christoph999** [comment]
Ok, then my comment won't be interesting :-)))
